// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebApplication1 {
	
	
	public partial class ranking {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DataList DataList2;
		
		protected System.Web.UI.WebControls.Label usuarioLabel;
		
		protected System.Web.UI.WebControls.Label puntuacionLabel;
		
		protected System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
	}
}
